"""Tilføj created_at til Friendship

Revision ID: 0f48c62cd5d5
Revises: 0da9931fd0fb
Create Date: 2025-04-13 11:44:51.961873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f48c62cd5d5'
down_revision = '0da9931fd0fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friendship', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
