"""Add timestamp to BeerLog

Revision ID: 4d81af59bb90
Revises: 
Create Date: 2025-03-15 11:53:03.148068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d81af59bb90'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('beer_log', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
