"""Tilføj allow_location til User

Revision ID: 9c6bb3c13154
Revises: f5f36af3d576
Create Date: 2025-05-11 18:02:28.541389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c6bb3c13154'
down_revision = 'f5f36af3d576'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('allow_location', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('allow_location')

    # ### end Alembic commands ###
